version: "3.8"
services:
  linuxgsm-pw-volume:
    image: gameservermanagers/gameserver:pw
    container_name: pwserver
    restart: unless-stopped
    volumes:
      - linuxgsm-pw:/data
    ports:
      - "8211:8211/udp"

volumes:
  linuxgsm-pw:
